#!/bin/bash

GOTO=$1

SCREEN_WIDTH=$(xwininfo -root | awk '$1=="Width:" {print $2}')
SCREEN_HEIGHT=$(xwininfo -root | awk '$1=="Height:" {print $2}')

X=$(( $SCREEN_WIDTH / 2 ))
Y=$SCREEN_HEIGHT

if [ $GOTO == "L" ];then
	wmctrl -r :ACTIVE: -b remove,maximized_horz,maximized_ver
	wmctrl -r :ACTIVE: -b add,maximized_ver
	wmctrl -r :ACTIVE: -e 0,0,0,$X,$Y
elif [ $GOTO == "R" ];then
	wmctrl -r :ACTIVE: -b remove,maximized_horz,maximized_ver
	wmctrl -r :ACTIVE: -b add,maximized_ver
	wmctrl -r :ACTIVE: -e 0,$X,0,$X,$Y
else
	echo "R or L ?"
fi
