######################################################################
# Automatically generated by qmake (3.0) Jum Feb 7 15:47:59 2014
######################################################################

TEMPLATE = app
QT = core gui widgets
TARGET = tes2
INCLUDEPATH += .

# Input
HEADERS += tes2.h
SOURCES += main.cpp tes2.cpp
