######################################################################
# Automatically generated by qmake (3.0) Sab Feb 8 06:45:23 2014
######################################################################

TEMPLATE = app
TARGET = tes3
INCLUDEPATH += .
QT = core gui widgets

# Input
HEADERS += gotocell.h
FORMS += frmCell.ui
SOURCES += gotocell.cpp main.cpp
