######################################################################
# Automatically generated by qmake (3.0) Jum Feb 7 13:59:58 2014
######################################################################

TEMPLATE = app
TARGET = tes1
INCLUDEPATH += .
QT = core gui widgets

# Input
SOURCES += tes1.cpp
